### ISSUE TITLE
Balancing on multiple columns work around

### ISSUE THREAD

**Issue by akshara-msft** [microsoft/responsible-ai-toolbox-mitigations#13]
Currently there is a work around in the end to end Jupyter notebook so that we can balance on two columns at the same time using any of the rebalancing techniques. While making API deseign changes to the Rebalance API, we should allow the user to specific multiple columns that they are interested in balancing on rather than creating a single column and balancing on that single column cohort

**Comment by mrfmendonca** [comment]
This has been fixed in PR #45, which introduces the ``CohortManager`` class. This class allows you to rebalance each cohort separately, without requiring any workarounds. More details can be found in the following notebook: ``/notebooks/cohort/cohort_manager.ipynb``.
