### ISSUE TITLE
No module named 'seaborn' when importing the "cohort" module

### ISSUE THREAD

**Issue by mrfmendonca** [microsoft/responsible-ai-toolbox-mitigations#51]
After installing the package using ``pip install raimitigations``, when I import any class from the ``cohort`` module, I get the following error:
```console
> from .utils import fetch_cohort_results, plot_value_counts_cohort
> import seaborn as sns
No module named 'seaborn'
```

The error doesn't occur if I install the library using ``pip install raimitigations[all]``.

To fix, add ``seaborn`` to the base set of dependencies, not only to the ``[all]`` dependency group.

**Comment by marah-abdin** [comment]
Addressed and resolved in release v1.1.1.
